### ISSUE TITLE
Windows下启动脚本抛出operation not permitted异常

### ISSUE THREAD

**Issue by vifird** [yansenlei/electron-asar-hot-updater#20]
```
[2019-09-27 23:54:25.767] [error] [Main] thred uncaughtException: EPERM: operation not permitted, open 'C:\Program Files (x86)\flicker\resources\updater-log.txt' Error: EPERM: operation not permitted, open 'C:\Program Files (x86)\flicker\resources\updater-log.txt'
    at Object.openSync (original-fs.js:447:3)
    at Object.writeFileSync (original-fs.js:1206:35)
    at Object.appendFileSync (original-fs.js:1252:6)
    at Object.log (C:\Program Files (x86)\flicker\resources\app.asar\dist\electron\main.js:1:154888)
    at Object.check (C:\Program Files (x86)\flicker\resources\app.asar\dist\electron\main.js:1:155243)
    at P._autoUpdate (C:\Program Files (x86)\flicker\resources\app.asar\dist\electron\main.js:127:57882)
    at P.start (C:\Program Files (x86)\flicker\resources\app.asar\dist\electron\main.js:127:56390)
    at L (C:\Program Files (x86)\flicker\resources\app.asar\dist\electron\main.js:127:58477)
    at Timeout._onTimeout (C:\Program Files (x86)\flicker\resources\app.asar\dist\electron\main.js:127:58751)
    at listOnTimeout (internal/timers.js:531:17)
```

**Comment by vifird** [comment]
package.json添加
```
"build": {
"win": {
      "requestedExecutionLevel": "requireAdministrator",
    }
}
```
